<?php

namespace AppBundle\Repository;

/**
 * SymfonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymfonyRepository extends \Doctrine\ORM\EntityRepository{
	
	public function getAll(){
		return $this->findBy([], ['starred' => 'DESC', 'path' => 'ASC', 'ip' => 'DESC']);
	}
	
	/**
	 * @return array
	 */
	public function getActives(){
		$q = $this->createQueryBuilder('s');
		$q
			->where('s.ip IS NOT NULL')
			->andWhere('s.port IS NOT NULL')
		;
		
		return $q->getQuery()->getResult();
	}
	
	public function getMaxPort(){
		dump($this->findOneBy([], ['port' => 'DESC']));die;
	}
	
}
