<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Symfony;

/**
 * SymfonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymfonyRepository extends \Doctrine\ORM\EntityRepository{
	
	/**
	 * Return all symfonies ordinated
	 *
	 * @return array
	 */
	public function getAll(){
		return $this->findBy([], ['starred' => 'DESC', 'path' => 'ASC', 'ip' => 'DESC']);
	}
	
	/**
	 * Return all active symfonies
	 *
	 * @return array
	 */
	public function getActives(){
		$q = $this->createQueryBuilder('s');
		$q
			->where('s.ip IS NOT NULL')
			->andWhere('s.port IS NOT NULL')
		;
		
		return $q->getQuery()->getResult();
	}
	
	/**
	 * Return the symfony with the max local ip
	 *
	 * @return Symfony
	 */
	public function getMaxLocalSymfonyByIp(){
		$q = $this->createQueryBuilder('s');
		$q
			->where($q->expr()->like('s.ip', ':ip'))
			->andWhere('s.port IS NOT NULL')
			->setParameter('ip','127.0.0.%')
			->orderBy('s.ip', 'DESC')
			->setMaxResults(1)
		;
		
		$results = $q->getQuery()->getResult();
		
		return count($results) > 0 ? $results[0] : null;
	}
	
	/**
	 * Return the symfony with the max local port
	 *
	 * @return Symfony
	 */
	public function getMaxLocalSymfonyByPort(){
		$q = $this->createQueryBuilder('s');
		$q
			->orderBy('s.port', 'DESC')
			->setMaxResults(1)
		;
		
		$results = $q->getQuery()->getResult();
		
		return count($results) > 0 ? $results[0] : null;
	}
	
}
