-
    url: 'https://symfony.com/'
    label: 'Symfony site'
    icon: 'favicon.ico'

-
    url: 'https://symfony.com/roadmap'
    label: 'Symfony roadmap'
    icon: 'favicon.ico'

-
    url: 'http://nux.net/secret'
    label: 'Symfony Secret Generator'
    icon: 'favicon.ico'

- DIVIDER

-
    url: 'http://www.yopmail.com/it/email-generator.php'
    label: 'YOPmail'
    icon: 'bundles/app/images/yopmail.gif'

-
    url: 'https://regex101.com/'
    label: 'Regex101'
    icon: 'bundles/app/images/regex.ico'

-
    url: 'https://jsoncompare.com/#!/simple/'
    label: 'JSONCompare (ex JSONLint)'
    icon: 'bundles/app/images/jsonlint.png'

-
    url: 'https://codebeautify.org/'
    label: 'Code beautify (a Swiss Army knife :D)'
    icon: 'bundles/app/images/cb.png'

-
    url: 'https://getbootstrap.com/docs/4.0/getting-started/introduction/'
    label: 'Bootstrap documentation'
    icon: 'bundles/app/images/bootstrap.ico'

-
    url: 'https://passwordsgenerator.net/'
    label: 'Secure Password Generator'
    icon: 'bundles/app/images/passgenerator.ico'
-
    url: 'https://www.browserstack.com/'
    label: 'BrowserStack'
    icon: 'bundles/app/images/browserstack.ico'