-
    url: 'https://symfony.com/'
    label: 'Symfony site'
    icon: 'favicon.ico'

-
    url: 'https://symfony.com/roadmap'
    label: 'Symfony roadmap'
    icon: 'favicon.ico'

-
    url: 'http://nux.net/secret'
    label: 'Symfony Secret Generator'
    icon: 'favicon.ico'

- DIVIDER

-
    url: 'http://www.yopmail.com/it/email-generator.php'
    label: 'YOPmail'
    icon: 'http://www.yopmail.com/favicon.gif'

-
    url: 'https://regex101.com/'
    label: 'Regex101'
    icon: 'https://regex101.com/favicon.ico'

-
    url: 'https://jsonlint.com/'
    label: 'JSONLint'
    icon: 'https://jsonlint.com/icons/icon-hires.png'

-
    url: 'https://getbootstrap.com/docs/4.0/getting-started/introduction/'
    label: 'Bootstrap documentation'
    icon: 'https://getbootstrap.com/favicon.ico'

-
    url: 'https://passwordsgenerator.net/'
    label: 'Secure Password Generator'
    icon: 'https://passwordsgenerator.net/fav/fav322.ico'
-
    url: 'https://www.browserstack.com/'
    label: 'BrowserStack'
    icon: 'https://www.browserstack.com/favicon.ico'